### PR TITLE
#30 detect current page on app load

### PR DESCRIPTION
**Pull request by aaronmgdr**
- detects hash/route changes more reactively
- moves AppRouter to be the Root component. 
- replace App.state.park with App.props.parkId

### CODE REVIEW

**Comment by aaronmgdr** [comment]
deployed this branch saturday 8pm

**Comment by prestonp** [comment]
LGTM!! :evergreen_tree:

**Comment by luqmaan** [comment]
:deciduous_tree: great idea flipping the structure around (router on top)

**Comment by aaronmgdr** [comment]
@luqmaan  well it was really @prestonp's idea / kinda a necessity

**Pull request merged**
