### PR TITLE
Get map element

### PR DESCRIPTION
**Pull request by johntyree**

### CODE REVIEW

**Comment by johntyree** [comment]
https://facebook.github.io/react/docs/more-about-refs.html

**Comment by aaronmgdr** [comment]
:deciduous_tree: 

although i'm thinking your gonna want to do more than just log something. 

one question and its not a change from this pr but is `id="map"` needed?

**Comment by luqmaan** [comment]
We use `#map` in the css: https://github.com/open-austin/austingreenmap/blob/d70257824575977ab8a45157f036adb2b1d01d08/client/scss/main.scss#L5

We can probably work around it, but this is simple for now.

**Comment by aaronmgdr** [comment]
also realized that the leaflet-react library needs an id and will add an one if we don't, so we are better off controlling  what it is than not

**Comment by luqmaan** [comment]
Ah good catch.

**Pull request merged**
